### ISSUE TITLE
Error when adding columns

### ISSUE THREAD

**Issue by radbrt** [radbrt/target-mssql#1]
Adding new columns to the source, which triggers and alter stable statement in the sink to add the new column, fails with a strange error.

With log-level debug, the logs show two notable entries:

A warning that the state is invalid: `[warning  ] Received state is invalid, incremental state has not been updated`. The log and sqlite DB shows seemingly correct state messages.

An error when executing the add column statement `ALTER TABLE feed ADD feed_link VARCHAR`: `sqlalchemy.exc.OperationalError: (pymssql._pymssql.OperationalError) Statement not executed or executed statement has no resultset`

When using the postgres tap, running the alter table statement manually works and the column is added. 

Running with the feed tap fails also after the column is added, when it tries to alter the column from VARCHAR to VARCHAR. Also here, the statement can be executed successfully in a SQL Client, which may suggest a general inability to execute SQL statements other than create table...

The situation can be reproduced by standing up the docker-compose file, adding a symbolic table to the source postgres DB, and running meltano twice. The first run should finish successfully, the second run will fail when meltano tries to add a table_version column.

**Comment by radbrt** [comment]
This works when "hardcoding" the alter table statement

```
        create_column_clause = sqlalchemy.schema.CreateColumn(
            sqlalchemy.Column(
                column_name,
                sql_type,
            )
        )

        try:
            self.connection.execute(
                f"""ALTER TABLE { str(full_table_name) } 
                ADD { str(create_column_clause) } """
            )
```

**Comment by edgarrmondragon** [comment]
> A warning that the state is invalid: [warning ] Received state is invalid, incremental state has not been updated.

If that warning is coming from Meltano, it may be due to this `print`:

https://github.com/radbrt/target-mssql/blob/88c2879f42f742110cae93e7849e644b8abbf207/target_mssql/sinks.py#L202

That's because Meltano looks at stdout of the target to pick up the state JSON.

**Comment by radbrt** [comment]
Somehow, this started working - I don’t have any real idea why, but in any case I’m on to new and more exciting error messages.
