### ISSUE TITLE
Handle bool datatypes?

### ISSUE THREAD

**Issue by radbrt** [radbrt/target-mssql#4]
Need to check how SQL Server handles bool datatypes, and make sure any bool types are written in at least a semi-sensible way.

**Comment by BuzzCutNorman** [comment]
@radbrt I just faced that as well.  Here is the issue which has a nice link for all the major SQL servers. There is also link to the PR that contains the code I used to deal with it.  Not my best fix but is works. 

- https://github.com/BuzzCutNorman/target-mssql/issues/1
- https://github.com/BuzzCutNorman/target-mssql/pull/2/files

**Comment by radbrt** [comment]
This seems to work reasonably now, closing.
